PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX otv: <http://www.ontologia.fr/OTB/otv#>
PREFIX alyra: <http://www.ontologia.fr/OTB/ALyrA_v.1.0#>
SELECT ?composer (COUNT(DISTINCT ?tlg) AS ?n) FROM <https://triplestore.talos-ai4ssh.uoc.gr:8890/datasets/Ancient-Lyric-Poetry-ALyrA-v1> WHERE { ?class rdfs:subClassOf* alyra:Archaic_Lyric_Composer . ?composer otv:instanceOf* ?class . ?composer alyra:tlgIdentifyingNumber ?tlg . } GROUP BY ?composer HAVING(COUNT(DISTINCT ?tlg)>1)